name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download build artifact (main.exe)
      uses: actions/download-artifact@v3
      with:
        name: programa
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: victorross/go_ci:${{ github.ref_name }}2